# Generated by Django 3.1.7 on 2021-04-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_time_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time_upload',
            new_name='date_added',
        ),
    ]
